"""updated

Revision ID: 030119206add
Revises: dee7cdf49648
Create Date: 2025-10-28 20:59:31.532171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030119206add'
down_revision = 'dee7cdf49648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('collection_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['point_id'], ['collection_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_points', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('collectors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collectors', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    with op.batch_alter_table('collection_points', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.drop_table('collection_schedules')
    # ### end Alembic commands ###
